### ISSUE TITLE
Errors out in defun erm-parse with Symbol's value as variable is void: need-syntax-check-p

### ISSUE THREAD

**Issue by ChasManRors** [zenspider/enhanced-ruby-mode#18]
error in process filter: enh-ruby-fontify-buffer: Symbol's value as variable is void: need-syntax-check-p
error in process filter: Symbol's value as variable is void: need-syntax-check-p
Revert buffer from file /Users/cmagid/Downloads/koans/about_strings.rb? (y or n)  y
error in process filter: enh-ruby-fontify-buffer: Symbol's value as variable is void: need-syntax-check-p
error in process filter: Symbol's value as variable is void: need-syntax-check-p
@zenspider @JEG2 
Thank you in advance.   I would have made a patch if I could have. ;)  everything I kludged with boundp was a flop

**Comment by pvenegas** [comment]
Managed to reproduce - this happened to me because I used to use ruby-mode, then switched to enh-ruby-mode at some point, and removed ruby-mode. But the .emacs.desktop file was calling desktop-create-buffer on some old files with ruby-mode. I removed all instances of ruby-mode from the desktop file and reloaded the desktop session, and it was fine.

**Comment by PierreRambaud** [comment]
Thank @pvenegas Fix my issue :wink:
