### ISSUE TITLE
Add font faces

### ISSUE THREAD

**Issue by Trevoke** [zenspider/enhanced-ruby-mode#30]
Hi,

I'm trying to create a color theme I like, and I find that some things aren't colorizable due to font-faces that don't exist. here are the code examples I've found so far which don't have separate font-faces:

1. %w[]
2. true / false
3. self
4. numbers
5. def / end
6. if / else / end

If there are no reasons to not add those, I'm willing to do the work :)

**Comment by zenspider** [comment]
This doesn't seem to be going anywhere. Should I close?

**Comment by Trevoke** [comment]
I mostly dropped the ball due to not being a developer for about a year, but I'm back at it now. I will start work on this, keeping in mind what we had done in the last issue, which was to provide a sane default for the people who don't like angry fruit salad :)

**Comment by zenspider** [comment]
No worries and no rush. Just want the issue list to reflect reality.

**Comment by zenspider** [comment]
I assume this is dead. Closing. Please reopen if you're _actively_ working on it.

**Comment by jsmestad** [comment]
@zenspider I would love to contribute an enhancement for some of these. I am currently trying to port highlighting from nanotech/jellybeans.vim. In order to get a closer match I want to add font faces for:

* symbol_literal (Input `Ripper.sexp(':asymbol')` | Ripper output: `[:symbol_literal, [:symbol, [:@ident, "asymbol", [1, 1]]]]`)
* `self`, `true`, `false` (Input `Ripper.sexp('self')` | Ripper output: `[[:var_ref, [:@kw, "self", [1, 0]]]]`)

I've been trying to follow previous patches [like this one](https://github.com/zenspider/enhanced-ruby-mode/commit/52c13a638a2dc680b4c90419a7d80dc0496796d5) to figure out how to add new font-faces, but I am a little stuck. Could you point me in the right direction?
